### PR TITLE
Feature/319 modal dialog role

### PR DESCRIPTION
**Pull request by tclindner**
I added a new error, E049, to address ticket #319. All existing fixtures have been updated to include role="document". A new test fixture has been added to ensure the new error is triggered if role="document" is forgotten for `.modal-dialog`. bootlint_test has been updated too.

### CODE REVIEW

**Comment by tclindner** [comment]
Hi @cvrebert it looks like the build is failing while running the cli against bootstrap's github pages. 
https://travis-ci.org/twbs/bootlint/builds/105590627#L1267

Both qunit and nodeunit run successfully. I believe the failure is occurring because role="document" is not required in v3's docs. How would you like me to handle resolving the failure?

**Comment by cvrebert** [comment]
Thanks, opened https://github.com/twbs/bootstrap/pull/19051 to fix v3's docs.

**Comment by cvrebert** [comment]
Travis now passes after having merged that PR.

**Comment by cvrebert** [comment]
@tclindner Looks good. Do you happen to be familiar with git rebasing?

**Comment by tclindner** [comment]
@cvrebert I am not familiar with rebasing. I tried to go back and review the PR for #318. I looks like you collapsed all commits in to a single commit. I found this article that talks about it linked from Github's help section (http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html). I will rebase and update the PR this evening. I'll make sure and do that before opening future PRs. I'm looking forward to becoming an active contributor. Thank you for all of the help!

P.S.: To help me learn, what is the biggest benefit of rebasing?

**Comment by cvrebert** [comment]
No worries, I'm happy to rebase it for you.

> what is the biggest benefit of rebasing?

It keeps the commit history a bit cleaner (particularly if a PR had to be revised one or more times), groups highly-interconnected changes into 1 atomic commit.
It can also make future `git bisect` sessions easier by avoiding intermediate commits where the program or test suite is broken/failing due to incomplete changes, although this is a secondary consideration and can also be avoided if one is very careful about the ordering and content of the commits.
Ultimately, it's somewhat a matter of taste. I just happen to come down on the pro-squash side.

>  I'm looking forward to becoming an active contributor. Thank you for all of the help!

We're happy to have you! One additional note for future reference: Try to make use of https://help.github.com/articles/closing-issues-via-commit-messages/ when making a PR that fixes/implements a particular extant issue.

**Comment by cvrebert** [comment]
Merged. Thanks!

**Comment by tclindner** [comment]
Thank you for the explanation! Thanks for recommending the commit message feature. I didn't know you could do that. That's pretty cool :) I'll make sure an do that in the future.

**Pull request closed without merging**
