### PR TITLE
Use more common way to determine if stdin should be read

### PR DESCRIPTION
**Pull request by hnrch02**
Refs #212
Refs #211

/cc @cvrebert @XhmikosR

### CODE REVIEW

**Comment by cvrebert** [comment]
So, here's my suggestion:
```js
if (!program.args.length) {
    program.args.push('-');   
}

program.args.forEach(function (pattern) {
    lintedFiles.push(pattern === '-' ? handleStdin() : handlePath(pattern));
});
```
(and remove `usedDash`)

And before you ask, yes, grep let's you specify `-` more than once.

**Comment by cvrebert** [comment]
@hnrch02 Ping.

**Comment by cvrebert** [comment]
@hnrch02 Ping.

**Comment by hnrch02** [comment]
@cvrebert LGTY now?

**Comment by cvrebert** [comment]
:shipit:

**Pull request merged**
