### PR TITLE
Fixed your dev dependencies. Out of date.

### PR DESCRIPTION
**Pull request by theCiupenator**

### CODE REVIEW

**Comment by jmervine** [comment]
Thanks for the contribution. 👍

**Comment by lirantal** [comment]
+1

**Comment by lirantal** [comment]
@cvrebert any chance to review and merge this PR for the dependencies to be up to date?
Build passes just fine.

Thanks!

**Comment by XhmikosR** [comment]
This is obsolete already. I started working on this and I'll make a PR tomorrow.

**Comment by lirantal** [comment]
@XhmikosR what do you mean obsolete? that newer packages have since then been released?

**Comment by XhmikosR** [comment]
That and the fact that it's not so simple. See the pull request I opened.

**Comment by lirantal** [comment]
@XhmikosR that's just rude to hi-jack someone else's PR.
Your eslint updates could be made in their own PR, that's fine. And with regards to the versions update you could just help out in this thread and suggest to update the commit with the update versions.

If your PR won't be merged for a month and new versions will be out I could also argue that it is obsolete and open a new PR. that doesn't sound too good, right?

**Comment by XhmikosR** [comment]
Not really no. Your PR was wrong. It's so simple/

I can merge my PR anytime I want.

**Comment by lirantal** [comment]
Once again, rude.
It's about collaboration, if you spotted an issue why not comment and suggest how to update?

**Comment by XhmikosR** [comment]
Rude or not, I'd rather do something myself right that spending time commenting.

Better luck the next time.

**Pull request closed without merging**
