### PR TITLE
My go at adding (some) Bootstrap 4 support

### PR DESCRIPTION
**Pull request by Herst**
Work in progress, early state ATM.

Note that this is a separate version just for BS4, so this pull request should **not** actually go into `master` (at least until there is a separate branch for BS3).

### CODE REVIEW

**Comment by Herst** [comment]
Classes which appear to be in `bootlint.js` but not in `bootstrap.css`:

- [ ] .carousel-control
- [ ] .checkbox
- [ ] .checkbox-inline
- [ ] .form-horizontal
- [ ] .glyphicon
- [ ] .hide
- [ ] .img-responsive
- [ ] .item
- [ ] .media-left
- [ ] .media-right
- [ ] .navbar-btn
- [ ] .navbar-left
- [ ] .navbar-right
- [ ] .panel
- [ ] .panel-body
- [ ] .panel-collapse
- [ ] .panel-footer
- [ ] .panel-heading
- [ ] .panel-title
- [ ] .pull-left
- [ ] .pull-right
- [ ] .radio
- [ ] .radio-inline

**Comment by Herst** [comment]
Removed Warnings/Errors:

- W002 (`X-UA-Compatible`)
- W010 (media pulls)
- W012 (`.container` required to be first child of `.navbar`)
- E002 (Bootstrap v2 `.span`s)
- E004 (nesting of containers)
- E027 (`.table-responsive` on outside div)

Warnings/Errors in need to be adapted/redone:

- [ ] W008 (tooltips on elements where `container` should be set to `body`) → What about `inpu-groups`?
- [ ] W014 (carousel stuff)

**Comment by Herst** [comment]
Updating `dist` now as well. Bookmarklet for my version:
```js
javascript:(function(){var s=document.createElement("script");s.onload=function(){bootlint.showLintReportForCurrentDocument([]);};s.src="https://rawgit.com/Herst/bootlint/v4/dist/browser/bootlint.js";document.body.appendChild(s)})();
```

**Comment by Herst** [comment]
BTW, collaboration is welcome!

**Comment by XhmikosR** [comment]
Wow, huge change list!

Not sure how to proceed though. Should we keep compatibility with v3? If so should we make a new branch for v4? Or can we have a common codebase?

@Johann-S @bardiharborow @cvrebert

**Comment by Herst** [comment]
IMHO, Bootstrap 3 and 4 are too different for the rules (the stuff inside ´src/bootstrap.js´) to be adapted to work with both version which is why in my fork I made it Bootstrap-4-only with a detection for most Bootstrap-3-specific classes (I also threw out everything concerning Bootstrap 2 since I am assuming nobody will switch from v2 to v4).

Of course the rest like the other code files inside `src/` could be shared, maybe in combination with the autodetection idea brought up in https://github.com/twbs/bootlint/issues/304#issuecomment-208870826

**Comment by XhmikosR** [comment]
Can someone chime in on how to proceed with this?

**Comment by Johann-S** [comment]
before that PR, bootlint handle Bootstrap 4 Alpha so we can continue to handle BS3 and BS4 if it's possible

**Comment by Herst** [comment]
FYI, I will have less time for working on this in the next two months.

**Comment by rrjanbiah** [comment]
Bump! Looks like an awesome work by @Herst that needs to get into official repo. Can someone from original author(s) check here? TIA

**Comment by XhmikosR** [comment]
@mdo: how about you give @Herst push rights to this repo, after you set up branch protection and stuff, so that we get things moving?

**Comment by Herst** [comment]
Now that the final v4 is out I feel like this should be started anew and done correctly this way, with tests first and PRs for every error/warning to remove/change/add (which then can be separately discussed). I still don't have all the time in the world and this count as a private project for me so I can't invest too much time so before I begin I would like to assess how much interest there even is for that and whether there are people willing to give a helping hand.

Also, it would probably be useful to also go use (the list of recent bug reports which were the result of wrong usage](https://github.com/twbs/bootstrap/issues) as a basis for a list of BS4-specific warnings/errors to add (e.g. those related to flex stuff).

Any update on how to handle Bootstrap 3? I would still prefer maintaining separate versions.

**Comment by Herst** [comment]
I started a clean new attempt with tests at https://github.com/Herst/bootlint-ng, this will be a proper fork with new name (**Bootlint-NG** instead of **Bootlint**), with tests and doing it step-by-step.

I am starting with a clean slate with all checks and tests disabled and using Pull Requests for each and every check with gets ported to Bootstrap v4+ (or totally new ones and those being deleted).

**Comment by XhmikosR** [comment]
@Herst: would you be interested in having access to the main repo instead? Sorry, I forgot to discuss this sooner with @mdo and the rest, but it seems we lack the manpower to handle this repo too.

**Comment by Herst** [comment]
@XhmikosR From what I understand there was still no decision on what would happen with Bootstrap 3 support. Since I intent to drop all support for it and only concentrate on the newest Bootstrap version, a fork with a different name makes sense in order to not cause confusion (an alternative would be different major numbers).

**Comment by XhmikosR** [comment]
@Herst: yeah, initially that was the plan because v3 is still very used. But I guess we could make one last release (maybe after downgrading cheerio since I had some issues there), tag it and move with v4.

The point is if you are willing to work on this, you might as well do it in the main repo :)

**Comment by Herst** [comment]
@XhmikosR What about the wiki pages though?
I think I stick to my fork for now and we will see later.

**Comment by XhmikosR** [comment]
I don't see the where's the issue. The wiki can be adapted as needed obviously.

But anyway, it's clear so far that you want your "own" fork.

**Comment by Herst** [comment]
@XhmikosR 
>  The wiki can be adapted as needed obviously._

But how to separate it between what concerns Bootstrap 3 and what concerns Bootstrap 4+? Separate the IDs? Have two sections per wiki page?

> But anyway, it's clear so far that you want your "own" fork.

Not necessarily, but now I started it and I like that it like a clean slate beginning when it comes to issues and pull requests (we could do the same here by simply closing all old issues/PRs like was done in the case of Bootstrap 4). But if you want I could switch back, would be even better if I could then get reviews and feedback from other people, especially those involved in the Bootstrap project.

**Comment by XhmikosR** [comment]
We can make a parent page which will hold the new v4 rules or something like that.

Anyway, like I said, where there's will there's a way. I don't see something causing issues if you want to work on v4 here.

**Comment by rrjanbiah** [comment]
> Updating `dist` now as well. Bookmarklet pointing to my version:
> 
> ```js
> javascript:(function(){var s=document.createElement("script");s.onload=function(){bootlint.showLintReportForCurrentDocument([]);};s.src="https://rawgit.com/Herst/bootlint/v4/dist/browser/bootlint.js";document.body.appendChild(s)})();
> ```

@Herst FYI This v4 bookmarklet doesn't work anymore due to GitHub blocking.

**Comment by Herst** [comment]
@rrjanbiah 
I am not working on that fork any more, instead I have branches in this project.

**Comment by Herst** [comment]
Updated Bootmarklet for the ["next"](https://github.com/twbs/bootlint/tree/next) branch where I am currently doing my work on:
```js
javascript:(function(){var s=document.createElement("script");s.onload=function(){bootlint.showLintReportForCurrentDocument([]);};s.src="https://cdn.jsdelivr.net/gh/twbs/bootlint@next/dist/browser/bootlint.js";document.body.appendChild(s)})();
```

See #431 for the current progress when it comes to porting existing checks, including what is still missing and where someone could help me.

**Comment by rrjanbiah** [comment]
@Herst 

You may want to use `https://cdn.jsdelivr.net/gh/twbs/bootlint@next/dist/browser/bootlint.js` instead of `https://raw.githack.com/twbs/bootlint/next/dist/browser/bootlint.js` due to CORS

**Pull request closed without merging**
