### PR TITLE
Switch to GitHub Actions CI.

### LINKED ISSUE #456: Switch to GitHub Actions CI

### PR DESCRIPTION
**Pull request by XhmikosR**
There's an issue with the CLI tests, even though the build isn't marked as failed, which we should fix too

If you expand Run tests or Run tests with Coveralls and scroll down to the cli tests, you will see this:

```
cli_test
TypeError: process.stdin.setEncoding is not a function
    at /home/runner/work/bootlint/bootlint/src/cli.js:55:27
    at Promise._execute (/home/runner/work/bootlint/bootlint/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/home/runner/work/bootlint/bootlint/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/home/runner/work/bootlint/bootlint/node_modules/bluebird/js/release/promise.js:79:10)
    at handleStdin (/home/runner/work/bootlint/bootlint/src/cli.js:48:16)
    at /home/runner/work/bootlint/bootlint/src/cli.js:89:44
✔ bootlint - Disable tags
    at Array.forEach (<anonymous>)
    at module.exports (/home/runner/work/bootlint/bootlint/src/cli.js:88:18)
    at Object.Disable tags (/home/runner/work/bootlint/bootlint/test/cli_test.js:84:9)
    at /home/runner/work/bootlint/bootlint/node_modules/nodeunit/lib/core.js:232:20
    at /home/runner/work/bootlint/bootlint/node_modules/nodeunit/deps/async.js:168:13
    at /home/runner/work/bootlint/bootlint/node_modules/nodeunit/deps/async.js:131:25
    at /home/runner/work/bootlint/bootlint/node_modules/nodeunit/deps/async.js:165:17
    at /home/runner/work/bootlint/bootlint/node_modules/nodeunit/deps/async.js:463:34
    at Object.setUp (/home/runner/work/bootlint/bootlint/test/cli_test.js:48:9)
    at /home/runner/work/bootlint/bootlint/node_modules/nodeunit/lib/core.js:260:35
```

Happens with all Node.js versions we test.

/CC @Johann-S @Herst 

Fixes #456

### CODE REVIEW

**Comment by XhmikosR** [comment]
This is what I mean

https://github.com/twbs/bootlint/pull/458/checks?check_run_id=201657667#step:14:92

It feels to me our cli tests aren't right.

**Comment by Herst** [comment]
It works now or am I seeing it incorrectly?

**Comment by XhmikosR** [comment]
It's there, just expand the test block and scroll down to the CLI tests.

**Comment by XhmikosR** [comment]
Alright, the GitHub Actions errors still seem to happen... https://github.com/twbs/bootlint/pull/458/checks?check_run_id=297329908#step:16:94

**Pull request merged**
