### PR TITLE
#315 - Add new lint for nested form groups

### LINKED ISSUE #315: Add check for attempted nesting of .form-group
Refs https://github.com/twbs/bootstrap/pull/17897

### PR DESCRIPTION
**Pull request by tclindner**
Resolves #315
- Add E050 to check for nested form groups.
- Add new fixtures to test the new lint
- Update bootlint_test to call new fixtures

### CODE REVIEW

**Comment by tclindner** [comment]
Hi @cvrebert would you be okay merging this PR in?

**Comment by tclindner** [comment]
Hi @cvrebert are you comfortable merging this PR? Thank you!

**Comment by tclindner** [comment]
Hi @cvrebert would you be okay merging this PR in? Thank you!

**Comment by tclindner** [comment]
Hi @XhmikosR are you comfortable merging this PR in? Thank you!!

**Comment by XhmikosR** [comment]
Thanks!

**Pull request merged**
