### PR TITLE
Fixed false positive W002

### PR DESCRIPTION
**Pull request by freezy-sk**
Fixed false positive W002 when chrome=1 is present in X-UA-Compatible meta tag. Fixes issue #338

### CODE REVIEW

**Comment by cvrebert** [comment]
Closing per https://github.com/twbs/bootlint/issues/338#issuecomment-164933784

**Comment by freezy-sk** [comment]
@cvrebert why have you closed this? my change was just about case insensitive checking for presence of `ie=edge` in `content` attribute

**Comment by martin-g** [comment]
It also changes from `exact match` to `contains`.  So `ie=edgeBLAH` will also pass.

**Comment by cvrebert** [comment]
Your description talks about `chrome=1` (and #338, which is regarding `chrome=1`), which is WontFix, so I closed without reading the patch.
After now reading your patch (which is about `IE=Edge` etc.), your description seems misleading.

At any rate, `IE=Edge` doesn't seem like a particularly sensible capitalization.
MS's own docs use `IE=edge` and H5BP uses `ie=edge` all-lowercase for the sake of compression. I don't see a great reason for folks to use other capitalization permutations besides those 2. If someone's using `iE=eDGe`, they need to see a psychiatrist.

**Comment by freezy-sk** [comment]
@cvrebert Thx, now I got your point. So what you think if I made another PR which will show message about deprecated chrome flag?

**Pull request closed without merging**
