### PR TITLE
#356 - new lint rule to disallow `.col-*-12` classes alone

### LINKED ISSUE #356: Disallow row only containing a single col-*-12
Something I see somewhat frequently from coworkers is  something like:

```
<div class="row">
    <div class="col-md-12">
        <p>stuff here</p>
    </div>
</div>
```

Which has the _exact same_ rendered output as

```
<p>stuff here</p>
```

Right now I have to manually hunt for `col-*-12` grid classes and look for the ones that would be useless like in my first example.  IMO, It would be a huge benefit to have a simple rule that looked for these useless grid implementations.

### PR DESCRIPTION
**Pull request by chrismbarr**
Fixes #356

### CODE REVIEW

**Comment by chrismbarr** [comment]
This has been sitting here for a few months now.  Any chance of getting this merged in?

**Comment by XhmikosR** [comment]
@chrismbarr: can you please rebase against latest master and fix any lint errors?

**Comment by chrismbarr** [comment]
@XhmikosR ok, done.

**Comment by XhmikosR** [comment]
@chrismbarr: thanks. I'll need the Wiki stuff like you did https://github.com/twbs/bootlint/issues/315#issuecomment-178326630

**Comment by XhmikosR** [comment]
Also, note, a merge is not a rebase. If it causes any issues you will need to rebase.

**Comment by chrismbarr** [comment]
Oops, sorry - in my normal git workflow we never use rebase.

Here are the docs to add for this rule:

-----

# E051

### `.col-*-12` classes used alone are not useful.

#### The contained elements do not need to be in a row/column at all since it will render the same way without using the grid in the first place. Using a combination of grid classes that includes a `.col-*-12` is ok.

Wrong:
```html
<div class="row">
    <div class="col-md-12">
        <p>Content here</p>
    </div>
</div>
```

Right:

```html
<p>Content here</p>
```

Another example:
```html
<div class="row">
    <div class="col-sm-6 col-md-12">
        <p>This is fine since it also uses other grid sizes</p>
    </div>
</div>
```

**Comment by XhmikosR** [comment]
You have used `W018` in the code.

**Comment by XhmikosR** [comment]
@chrismbarr: this needs another fetch and rebase.

About the Wiki stuff you pasted above, is only the identifier wrong?

**Comment by XhmikosR** [comment]
@chrismbarr: this isn't right. My patches shouldn't be here.

**Comment by chrismbarr** [comment]
Oops, you're right.  Corrected the ID. Yes that was the only thing wrong with the docs.

I tried a rebase... sorry it's new to me, I'm thinking I did it wrong.  Would you prefer that I just close this and make a fresh PR, or merge master into this branch again?

**Comment by XhmikosR** [comment]
I will, rebase your branch but honestly it's just too easy and you will need to learn to do it for your other PRs because they will conflict as we merge...

**Comment by XhmikosR** [comment]
@chrismbarr: please go through all your PRs and this one and enable Allow edits from maintainers.

**Comment by chrismbarr** [comment]
Ok done.  Sorry for all the trouble here

**Comment by XhmikosR** [comment]
No worries. It's just it would save me a lot of time in the future if you properly rebased and fixed any build failures instead of me doing it.

**Comment by XhmikosR** [comment]
We get an error in BS v3 docs linting. I'll need to take care of that and then merge this.

**Comment by XhmikosR** [comment]
@mdo: can you chime in for this change? For example for the BS v3 docs we get

```
bootstrap/_gh_pages/browser-bugs/index.html:109:9 W018 `.col-*-12` classes used alone are not useful. This element does not need to be in a row/column since it will render the same way without using the grid here at all
```

**Comment by XhmikosR** [comment]
This is how I went to solve this for our docs  https://github.com/twbs/bootstrap/compare/v3-dev...v3-dev-xmr-col-12-fw

**Pull request closed without merging**
